export const OBTENER_HORARIOS = 'OBTENER_HORARIOS';
export const OBTENER_SERVICIOS = 'OBTENER_SERVICIOS';
export const AGENDAR_HORA = 'AGENDAR_HORA';
export const SERVICIO_ACTUAL = 'SERVICIO_ACTUAL';
