export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const OBTENER_HORARIOS = 'OBTENER_HORARIOS';
export const OBTENER_SERVICIOS = 'OBTENER_SERVICIOS';
export const AGENDAR_HORA = 'AGENDAR_HORA';
export const SERVICIO_ACTUAL = 'SERVICIO_ACTUAL';
export const OBTENER_AGENDAS = 'OBTENER_AGENDAS';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
